import type { Metadata } from 'next'
import { Jura } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import StoreProvider from './StoreProvider'

const inter = Jura({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <nav className="w-full p-2 border-b border-slate-400">
            <Navbar />
          </nav>
          <main className="flex min-h-screen flex-col items-center gap-3 p-12">
            {children}
          </main>
        </body>
      </html>
    </StoreProvider>
  )
}
